logger:
    level: debug
db_maria:
    host: 127.0.0.1
    port: 3306
    user: pmacctuser
    pw: pmacct01!
    database: pmacct
    poolLimit: 10
    sshUse: Y
    sshHost: 180.210.48.229
    sshPort: 22022
    sshUser: honguser01
    sshPw: ghdtmdals01!
